### ISSUE TITLE
ERROR: ldap_entry is not a legal parameter in an Ansible task or handler

### ISSUE THREAD

**Issue by ganto** [debops/ansible-auth#10]
I guess commit ab6c0e5 introduced the following problem. If I try to run `debops` on a fresh installation it fails with:

    debops@admin01:~/inofix-test$ debops -vvvv
    Running Ansible playbook from:
    /var/depops/.local/share/debops/debops-playbooks/playbooks/site.yml ...
    ERROR: ldap_entry is not a legal parameter in an Ansible task or handler

**Comment by drybjed** [comment]
`ldap_entry` and `ldap_attr` modules are provided in https://github.com/debops/debops-playbooks repsitory, you should update it.

**Comment by ganto** [comment]
I'm already running the latest version:

    debops@admin01:~/.local/share/debops/debops-playbooks$ git reflog
    953501a HEAD@{0}: clone: from https://github.com/debops/debops-playbooks

Reverting https://github.com/debops/ansible-auth to 36b38d6 fixes the problem for the moment.

**Comment by drybjed** [comment]
@ganto OK, let's try other things... What Ansible version do you use? Are `ldap_attr` and `ldap_entry` modules present in `/var/debops/.local/share/debops/debops-playbooks/playbooks/library/` subdirectories?

**Comment by ganto** [comment]
I'm running debops on a fresh installed Debian jessie with ansible-1.7.2+dfsg-2.

The python modules are there:
debops@admin01:~$ ls -l /var/depops/.local/share/debops/debops-playbooks/playbooks/library/database/ldap/
total 24
-rw-r--r-- 1 debops debops     0 Feb 24 22:30 __init__.py
-rw-r--r-- 1 debops debops 10595 Feb 24 22:30 ldap_attr.py
-rw-r--r-- 1 debops debops  8343 Feb 24 22:30 ldap_entry.py

**Comment by drybjed** [comment]
@ganto I see. Unfortunately, Ansible 1.7.2 is too old now, you need at least Ansible 1.8.0+. You can install it using the `bootstrap-ansible.sh` script in https://github.com/debops/debops repository.

**Comment by ganto** [comment]
Ok, I see. Maybe you should update the README.md then. Thanks a lot for your help :+1:

**Comment by ganto** [comment]
Confirm: Now using ansible-1.9-0.git201502241354~unstable which doesn't show the issue.

**Comment by drybjed** [comment]
@ganto Thanks for the confirmation. I'll try updating the README files soon. Have fun. :-)
